# GitHub Contribution Hack Configuration

# List of repositories to make contributions to
# Format: username/repository-name
repositories:
  - github-contribution-hack/demo-repo1
  - github-contribution-hack/demo-repo2

# Minimum and maximum number of commits per repository per run
min_commits: 1
max_commits: 3

# Interval between contribution runs (in hours)
min_interval: 12
max_interval: 24

split_commits:
  enabled: true
  max_lines_per_commit: 5
  message_prefix: "Automated commit"

intelligent_patterns:
  enabled: true
  content_types:
    - documentation
    - code
    - config
  time_distribution: poisson
  markov_source: "commit_patterns.json"
  max_commit_size: 100
  min_commit_size: 10 